# -*- coding: utf-8 -*-
"""Problem2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7-t7oT5kyKTVQ5LywSx4FYeagJ3Ukh1

#Set up and Load Dataset
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import random

# Load data
with open("TrainingNames.txt", "r") as f:
    names = [line.strip().lower() for line in f]

# Build vocab
chars = sorted(list(set("".join(names))))
chars = ['<SOS>', '<EOS>'] + chars

char_to_idx = {ch: i for i, ch in enumerate(chars)}
idx_to_char = {i: ch for ch, i in char_to_idx.items()}

vocab_size = len(chars)

"""#Encode names"""

encoded_names = []

for name in names:
    seq = [char_to_idx['<SOS>']] + \
          [char_to_idx[ch] for ch in name] + \
          [char_to_idx['<EOS>']]
    encoded_names.append(seq)

inputs = []
targets = []

for seq in encoded_names:
    for i in range(len(seq) - 1):
        inputs.append(seq[:i+1])
        targets.append(seq[i+1])

"""#Data Loader"""

from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import TensorDataset, DataLoader

inputs = [torch.tensor(seq) for seq in inputs]
inputs_padded = pad_sequence(inputs, batch_first=True, padding_value=0)

targets = torch.tensor(targets)

dataset = TensorDataset(inputs_padded, targets)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

"""#Vanilla RNN"""

class RNNModel(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.rnn = nn.RNN(embed_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x):
        x = self.embedding(x)
        out, _ = self.rnn(x)
        out = self.fc(out[:, -1, :])
        return out

"""#Training Loop"""

model = RNNModel(vocab_size, 32, 64)

optimizer = torch.optim.Adam(model.parameters(), lr=0.003)
loss_fn = nn.CrossEntropyLoss()

epochs = 10

for epoch in range(epochs):
    total_loss = 0

    for x, y in loader:
        optimizer.zero_grad()

        out = model(x)
        loss = loss_fn(out, y)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

"""Generated names"""

def generate_name(model, max_len=10):
    model.eval()

    seq = [char_to_idx['<SOS>']]

    for _ in range(max_len):
        x = torch.tensor(seq).unsqueeze(0)

        out = model(x)
        probs = torch.softmax(out, dim=1).detach().numpy()[0]

        # remove SOS from sampling
        valid_indices = list(range(vocab_size))
        valid_indices.remove(char_to_idx['<SOS>'])

        filtered_probs = [probs[i] for i in valid_indices]

        idx = random.choices(valid_indices, weights=filtered_probs)[0]
        char = idx_to_char[idx]

        # stop condition
        if char == '<EOS>' and len(seq) > 3:
            break

        # avoid repetition
        if len(seq) > 2 and idx == seq[-1]:
            continue

        seq.append(idx)

    # clean output
    name = "".join(
        ch for ch in [idx_to_char[i] for i in seq[1:]]
        if ch not in ['<SOS>', '<EOS>']
    )

    return name.capitalize()

print("\nGenerated Names (RNN):")
for _ in range(10):
    print(generate_name(model))

"""#For evaluation metric"""

print("\nGenerated Names (RNN):")
for _ in range(50):
    print(generate_name(model))

"""#BLSTM Model"""

class BLSTMModel(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)

        self.lstm = nn.LSTM(
            embed_dim,
            hidden_dim,
            batch_first=True,
            bidirectional=True
        )

        self.fc = nn.Linear(hidden_dim * 2, vocab_size)

    def forward(self, x):
        x = self.embedding(x)

        out, _ = self.lstm(x)

        out = self.fc(out[:, -1, :])   # last timestep

        return out

model = BLSTMModel(vocab_size, 32, 64)

optimizer = torch.optim.Adam(model.parameters(), lr=0.003)
loss_fn = nn.CrossEntropyLoss()

epochs = 10

for epoch in range(epochs):
    total_loss = 0

    for x, y in loader:
        optimizer.zero_grad()

        out = model(x)
        loss = loss_fn(out, y)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

print("\nGenerated Names (BLSTM):")
for _ in range(10):
    print(generate_name(model))

print("\nGenerated Names (BLSTM):")
for _ in range(50):
    print(generate_name(model))

"""#Attention model"""

class AttentionModel(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)

        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)

        # Attention scoring
        self.attn = nn.Linear(hidden_dim, 1)

        self.fc = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x):
        x = self.embedding(x)

        out, _ = self.lstm(x)   # (batch, seq_len, hidden)

        # Compute attention scores
        attn_scores = self.attn(out)             # (batch, seq_len, 1)
        attn_weights = torch.softmax(attn_scores, dim=1)

        # Weighted sum (context vector)
        context = torch.sum(attn_weights * out, dim=1)   # (batch, hidden)

        out = self.fc(context)

        return out

model = AttentionModel(vocab_size, 32, 64)

optimizer = torch.optim.Adam(model.parameters(), lr=0.003)
loss_fn = nn.CrossEntropyLoss()

epochs = 10

for epoch in range(epochs):
    total_loss = 0

    for x, y in loader:
        optimizer.zero_grad()

        out = model(x)
        loss = loss_fn(out, y)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

print("\nGenerated Names (Attention):")
for _ in range(10):
    print(generate_name(model))

print("\nGenerated Names (Attention):")
for _ in range(50):
    print(generate_name(model))

generated_names = [generate_name(model) for _ in range(100)]

def compute_novelty(generated, training):
    training_set = set(name.lower() for name in training)

    novel = 0
    for name in generated:
        if name.lower() not in training_set:
            novel += 1

    return novel / len(generated)

def compute_diversity(generated):
    unique_names = set(generated)
    return len(unique_names) / len(generated)

novelty = compute_novelty(generated_names, names)
diversity = compute_diversity(generated_names)

print("Novelty:", novelty)
print("Diversity:", diversity)

print("\nSample Generated Names:")
for name in generated_names[:10]:
    print(name)

"""#Evaluation metric"""

import pandas as pd
from difflib import SequenceMatcher


# HELPER: SIMILARITY FUNCTION

def similarity(a, b):
    return SequenceMatcher(None, a, b).ratio()


# NORMALIZE NAMES

def normalize(names):
    return [name.lower().strip() for name in names]


# NOVELTY (STRONG VERSION)

def compute_novelty(generated, training, threshold=0.8):
    training = normalize(training)
    generated = normalize(generated)

    novel_count = 0

    for g in generated:
        is_novel = True

        for t in training:
            if similarity(g, t) > threshold:
                is_novel = False
                break

        if is_novel:
            novel_count += 1

    return novel_count / len(generated)


# DIVERSITY

def compute_diversity(generated):
    generated = normalize(generated)
    unique = len(set(generated))
    return unique / len(generated)



# MAIN EVALUATION FUNCTION
def evaluate_model(model_name, generated_names, training_names):
    novelty = compute_novelty(generated_names, training_names)
    diversity = compute_diversity(generated_names)

    return {
        "Model": model_name,
        "Novelty": round(novelty, 4),
        "Diversity": round(diversity, 4)
    }



# INPUT (YOU FILL THESE)


# Load training names
with open("TrainingNames.txt") as f:
    training_names = [line.strip() for line in f]

# Replace these with your outputs
rnn_generated = [
"Hdvl",
"Otg",
"Tabdx",
"Uxf",
"Fubk",
"Druw",
"Sjobhah",
"Nntdydedr",
"Nobl",
"Fwadq",
"Awtf",
"Pcusyuq",
"Irovm",
"Rjdy",
"Hve",
"Jviq",
"Vitf",
"Tng",
"Kmsab",
"Cmagy",
"Njg",
"Ydfea",
"Blwjc",
"Cghshah",
"Verz",
"Hjryk",
"Parlv",
"Kcozha",
"Kra",
"Aornq",
"Tsmchd",
"Xpq",
"Ekjvbr",
"Damj",
"Mdipt",
"Djex",
"Zoat",
"Egi",
"Pbrhzijad",
"Zsg",
"Xya",
"Nil",
"Semnheko",
"Ejdjc",
"Noielno",
"Mamiev",
"Dfo",
"Drm",
"Oapmg",
"Uok"
]

blstm_generated = [
"Thmdr",
"Mtnhx",
"Yao",
"Hpadziez",
"Hli",
"Pgtdvjo",
"Hjelf",
"Agshv",
"Loibhktv",
"Byshehsah",
"Dvdrcj",
"Urag",
"Lmektkd",
"Cmd",
"Prjyke",
"Rata",
"Zrow",
"Gnaus",
"Kt",
"Hboshr",
"Gpiaox",
"Nsn",
"Oasmn",
"Ibh",
"Sn",
"Bjhaf",
"Laihsg",
"Jlkai",
"Ayu",
"Hmi",
"Rhdb",
"Tpy",
"Va",
"Vi",
"Womjct",
"Dbvrw",
"Raheu",
"Cmh",
"Eyrkau",
"Zwhg",
"Laidmy",
"Nxae",
"Nygu",
"Wmb",
"Javg",
"Gsvyh",
"Smphq",
"Entehf",
"Naehr",
"Nga"

]

attention_generated = [
"Om",
"Hqk",
"Sjueshv",
"Kpru",
"Sutx",
"Uym",
"Idyb",
"Wdj",
"Xoto",
"Yapl",
"Khil",
"Rix",
"Azri",
"Rjph",
"Ksbhah",
"Yfga",
"Eiu",
"Pubpf",
"Cdbx",
"Thrta",
"Ita",
"Ysy",
"Rkm",
"Rcau",
"Rdpo",
"Exsth",
"Gfes",
"Irth",
"Sqha",
"Ydni",
"Fswhth",
"Eldefw",
"Ua",
"Vde",
"Rtadrkiao",
"My",
"Ahsif",
"Rlki",
"Rdqe",
"Msy",
"Sufevshq",
"Znebg",
"Pwekabr",
"Qhx",
"Drk",
"Rgati",
"Ksr",
"Ig",
"Fgza",
"Vqa"

]

# -------------------------------
# EVALUATE
# -------------------------------
results = []

results.append(evaluate_model("RNN", rnn_generated, training_names))
results.append(evaluate_model("BLSTM", blstm_generated, training_names))
results.append(evaluate_model("Attention", attention_generated, training_names))

df = pd.DataFrame(results)

# -------------------------------
# SAVE CSV
# -------------------------------
df.to_csv("evaluation.csv", index=False)

print(df)