# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hRw939aZeVpcv3bhcn727zlUu0Pa8k48

#Setup
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile

zip_path = "/content/drive/MyDrive/data.zip"
extract_path = "/content/data"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import shutil

# move raw folder up
shutil.move("/content/data/data/raw", "/content/data/raw")

import os
print(os.listdir("/content/data/raw"))

"""#PREPROCESSING (clean + tokenize + corpus)"""

import os
import re
import string

# -------------------------------
# CLEANING FUNCTION
# -------------------------------
def clean_text(text):
    """
    Cleans raw text by:
    - Removing HTML tags
    - Removing numbers
    - Removing punctuation
    - Removing extra spaces
    """

    # Remove HTML tags (if any)
    text = re.sub(r'<.*?>', ' ', text)

    # Remove numbers
    text = re.sub(r'\d+', ' ', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Convert to lowercase
    text = text.lower()

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text)

    return text.strip()


# -------------------------------
# TOKENIZATION FUNCTION
# -------------------------------
def tokenize(text):
    """
    Splits cleaned text into words
    """
    return text.split()


# -------------------------------
# PROCESS SINGLE FILE
# -------------------------------
def process_file(file_path):
    """
    Reads and processes a file
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        text = f.read()

    cleaned = clean_text(text)
    tokens = tokenize(cleaned)

    return tokens


# -------------------------------
# BUILD CORPUS
# -------------------------------
def build_corpus(folder_path):
    """
    Reads all files and builds:
    - corpus (list of sentences)
    - all_tokens (flat list)
    """

    corpus = []
    all_tokens = []

    for file in os.listdir(folder_path):
        file_path = os.path.join(folder_path, file)

        tokens = process_file(file_path)

        corpus.append(tokens)
        all_tokens.extend(tokens)

    return corpus, all_tokens


# -------------------------------
# DATASET STATISTICS
# -------------------------------
def dataset_stats(corpus, all_tokens):
    """
    Prints required statistics
    """

    num_documents = len(corpus)
    total_tokens = len(all_tokens)
    vocab = set(all_tokens)
    vocab_size = len(vocab)

    print("Number of documents:", num_documents)
    print("Total tokens:", total_tokens)
    print("Vocabulary size:", vocab_size)

    return num_documents, total_tokens, vocab_size


# -------------------------------
# MAIN EXECUTION
# -------------------------------
if __name__ == "__main__":

    data_folder = "/content/data/raw"   # 👈 your path

    corpus, all_tokens = build_corpus(data_folder)

    dataset_stats(corpus, all_tokens)

    # print sample tokens
    print("\nSample tokens:", all_tokens[:20])

pip install wordcloud

"""#Word cloud analysis"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

def plot_wordcloud(all_tokens):
    """
    Generates and displays word cloud
    """

    text = " ".join(all_tokens)

    wc = WordCloud(width=800, height=400, background_color='white')
    wc.generate(text)

    plt.figure(figsize=(10,5))
    plt.imshow(wc, interpolation='bilinear')
    plt.axis('off')
    plt.title("Word Cloud of IIT Jodhpur Dataset")
    plt.show()

plot_wordcloud(all_tokens)

"""#CBOW model"""

import torch
import torch.nn as nn
import torch.optim as optim


# STEP 1: BUILD VOCABULARY

def build_vocab(tokens):
    vocab = list(set(tokens))
    word_to_idx = {word: i for i, word in enumerate(vocab)}
    idx_to_word = {i: word for word, i in word_to_idx.items()}
    return vocab, word_to_idx, idx_to_word



# STEP 2: CREATE TRAINING DATA

def generate_cbow_data(tokens, window_size=2):
    data = []

    for i in range(window_size, len(tokens) - window_size):
        context = []
        for j in range(-window_size, window_size + 1):
            if j != 0:
                context.append(tokens[i + j])

        target = tokens[i]
        data.append((context, target))

    return data


# -------------------------------
# STEP 3: CBOW MODEL

class CBOW(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(CBOW, self).__init__()

        self.embeddings = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, vocab_size)

    def forward(self, context_idxs):
        embeds = self.embeddings(context_idxs)

        # Average context embeddings
        avg_embed = torch.mean(embeds, dim=0)

        out = self.linear(avg_embed)
        log_probs = torch.log_softmax(out, dim=0)

        return log_probs



# STEP 4: TRAINING FUNCTION

def train_cbow(data, word_to_idx, vocab_size, embedding_dim=100, epochs=10, lr=0.01):

    model = CBOW(vocab_size, embedding_dim)
    loss_function = nn.NLLLoss()
    optimizer = optim.SGD(model.parameters(), lr=lr)

    for epoch in range(epochs):
        total_loss = 0

        for context, target in data:

            context_idxs = torch.tensor([word_to_idx[w] for w in context], dtype=torch.long)
            target_idx = torch.tensor([word_to_idx[target]], dtype=torch.long)

            model.zero_grad()

            log_probs = model(context_idxs)

            loss = loss_function(log_probs.view(1, -1), target_idx)

            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

    return model


# -------------------------------
# STEP 5: RUN EVERYTHING
# -------------------------------

#  Use your existing tokens from preprocessing
tokens = all_tokens

# Build vocab
vocab, word_to_idx, idx_to_word = build_vocab(tokens)

# Generate training data
training_data = generate_cbow_data(tokens, window_size=2)

print("Total training samples:", len(training_data))

# Train model
model = train_cbow(
    training_data,
    word_to_idx,
    vocab_size=len(vocab),
    embedding_dim=100,
    epochs=10
)


# -------------------------------
# STEP 6: TEST SIMILARITY
# -------------------------------
def get_embedding(word):
    return model.embeddings(torch.tensor(word_to_idx[word]))

def cosine_similarity(w1, w2):
    v1 = get_embedding(w1)
    v2 = get_embedding(w2)
    return torch.dot(v1, v2) / (torch.norm(v1) * torch.norm(v2))


print("\nSimilarity(student, research):", cosine_similarity("student", "research"))

"""#CBOW Neighbours"""

def get_top_neighbors(word, top_k=5):
    target_vec = get_embedding(word)

    similarities = []

    for other_word in word_to_idx:
        if other_word != word:
            sim = cosine_similarity(word, other_word).item()
            similarities.append((other_word, sim))

    # Sort by similarity
    similarities.sort(key=lambda x: x[1], reverse=True)

    return similarities[:top_k]


#  Test words
words_to_test = ["research", "student", "phd", "exam"]

for word in words_to_test:
    if word in word_to_idx:
        print(f"\nTop neighbors for '{word}':")
        neighbors = get_top_neighbors(word)
        for w, score in neighbors:
            print(f"{w} → {score:.4f}")
    else:
        print(f"\n'{word}' not in vocabulary")

"""#Skip Gram"""

import torch
import torch.nn as nn
import torch.optim as optim
import random

# -------------------------------
# STEP 1: GENERATE SKIPGRAM DATA
# -------------------------------
def generate_skipgram_data(tokens, window_size=2):
    pairs = []

    for i in range(window_size, len(tokens) - window_size):
        target = tokens[i]

        for j in range(-window_size, window_size + 1):
            if j != 0:
                context = tokens[i + j]
                pairs.append((target, context))

    return pairs


# -------------------------------
# STEP 2: MODEL
# -------------------------------
class SkipGramNeg(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(SkipGramNeg, self).__init__()

        # Input embedding (target word)
        self.in_embeddings = nn.Embedding(vocab_size, embedding_dim)

        # Output embedding (context word)
        self.out_embeddings = nn.Embedding(vocab_size, embedding_dim)

    def forward(self, target_idx, context_idx, negative_idxs):
        target_embed = self.in_embeddings(target_idx)
        context_embed = self.out_embeddings(context_idx)

        # Positive score
        pos_score = torch.dot(target_embed, context_embed)
        pos_loss = torch.log(torch.sigmoid(pos_score))

        # Negative sampling loss
        neg_embed = self.out_embeddings(negative_idxs)
        neg_score = torch.matmul(neg_embed, target_embed)

        neg_loss = torch.sum(torch.log(torch.sigmoid(-neg_score)))

        return -(pos_loss + neg_loss)


# -------------------------------
# STEP 3: NEGATIVE SAMPLING
# -------------------------------
def get_negative_samples(vocab_size, k):
    return torch.tensor(random.sample(range(vocab_size), k), dtype=torch.long)


# -------------------------------
# STEP 4: TRAINING
# -------------------------------
def train_skipgram(pairs, word_to_idx, vocab_size, embedding_dim=100, epochs=5, lr=0.01, neg_samples=5):

    model = SkipGramNeg(vocab_size, embedding_dim)
    optimizer = optim.SGD(model.parameters(), lr=lr)

    for epoch in range(epochs):
        total_loss = 0

        for target, context in pairs:

            target_idx = torch.tensor(word_to_idx[target], dtype=torch.long)
            context_idx = torch.tensor(word_to_idx[context], dtype=torch.long)

            negative_idxs = get_negative_samples(vocab_size, neg_samples)

            model.zero_grad()

            loss = model(target_idx, context_idx, negative_idxs)

            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

    return model


# -------------------------------
# STEP 5: RUN
# -------------------------------
pairs = generate_skipgram_data(all_tokens, window_size=2)

print("Total skip-gram pairs:", len(pairs))

skip_model = train_skipgram(
    pairs,
    word_to_idx,
    vocab_size=len(vocab),
    embedding_dim=100,
    epochs=10
)

def get_embedding_sg(word):
    return skip_model.in_embeddings(torch.tensor(word_to_idx[word]))

def cosine_similarity_sg(w1, w2):
    v1 = get_embedding_sg(w1)
    v2 = get_embedding_sg(w2)
    return torch.dot(v1, v2) / (torch.norm(v1) * torch.norm(v2))

"""#Neighbours for skipgram"""

def get_top_neighbors_sg(word, top_k=5):
    similarities = []

    for other_word in word_to_idx:
        if other_word != word:
            sim = cosine_similarity_sg(word, other_word).item()
            similarities.append((other_word, sim))

    similarities.sort(key=lambda x: x[1], reverse=True)

    return similarities[:top_k]


words_to_test = ["research", "student", "Ph.D", "exam"]

for word in words_to_test:
    if word in word_to_idx:
        print(f"\nTop neighbors (Skip-gram) for '{word}':")
        neighbors = get_top_neighbors_sg(word)
        for w, score in neighbors:
            print(f"{w} → {score:.4f}")
    else:
        print(f"\n'{word}' not in vocabulary")

with open("/content/clean_corpus.txt", "w") as f:
    for sentence in corpus:
        f.write(" ".join(sentence) + "\n")

from google.colab import files
files.download("/content/clean_corpus.txt")

print("btech" in word_to_idx)
print("ug" in word_to_idx)
print("pg" in word_to_idx)

"""#Embeddings"""

def analogy(word1, word2, word3, top_k=5):
    """
    word1 : word2 :: word3 : ?
    """

    if word1 not in word_to_idx or word2 not in word_to_idx or word3 not in word_to_idx:
        print("One of the words not in vocabulary")
        return

    vec = (
        get_embedding(word2)
        - get_embedding(word1)
        + get_embedding(word3)
    )

    similarities = []

    for word in word_to_idx:
        if word not in [word1, word2, word3]:
            word_vec = get_embedding(word)
            sim = torch.dot(vec, word_vec) / (torch.norm(vec) * torch.norm(word_vec))
            similarities.append((word, sim.item()))

    similarities.sort(key=lambda x: x[1], reverse=True)

    return similarities[:top_k]

"""#Analogy"""

print("\nAnalogy 1:")
print(analogy("phd", "research", "btech"))

print("\nAnalogy 2:")
print(analogy("data", "analysis", "visualization"))

print("\nAnalogy 3:")
print(analogy("design", "system", "data"))

"""#VISUALIZATION"""

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

def visualize_embeddings(words):
    vectors = []

    for word in words:
        if word in word_to_idx:
            vec = get_embedding(word).detach().numpy()
            vectors.append(vec)
        else:
            print(f"{word} not in vocab")

    # PCA to reduce to 2D
    pca = PCA(n_components=2)
    reduced = pca.fit_transform(vectors)

    # Plot
    plt.figure(figsize=(10, 8))

    for i, word in enumerate(words):
        if word in word_to_idx:
            x, y = reduced[i]
            plt.scatter(x, y)
            plt.text(x + 0.01, y + 0.01, word)

    plt.title("Word Embeddings Visualization (CBOW)")
    plt.show()

words = [
    "student", "research", "engineering", "data",
    "analysis", "design", "system", "visualization",
    "technology", "learning", "model", "project"
]

visualize_embeddings(words)

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Select words to visualize
words = ["research", "student", "phd", "exam", "data", "system",
         "learning", "model", "analysis", "engineering", "technology"]

# Get embeddings from Skip-gram
vectors = []

valid_words = []
for word in words:
    if word in word_to_idx:
        vec = skip_model.in_embeddings(
            torch.tensor(word_to_idx[word])
        ).detach().numpy()
        vectors.append(vec)
        valid_words.append(word)

# Apply PCA
pca = PCA(n_components=2)
reduced = pca.fit_transform(vectors)

# Plot
plt.figure(figsize=(8,6))
plt.scatter(reduced[:,0], reduced[:,1])

for i, word in enumerate(valid_words):
    plt.annotate(word, (reduced[i,0], reduced[i,1]))

plt.title("Word Embeddings Visualization (Skip-gram)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

"""#Models using genism"""

pip install gensim

corpus  # ← perfect for gensim

from gensim.models import Word2Vec

# CBOW (sg=0)
cbow_model = Word2Vec(
    sentences=corpus,
    vector_size=100,
    window=5,
    min_count=1,
    sg=0   # CBOW
)

# Skip-gram (sg=1)
skipgram_model = Word2Vec(
    sentences=corpus,
    vector_size=100,
    window=5,
    min_count=1,
    sg=1
)

print("\nGensim CBOW - research:")
print(cbow_model.wv.most_similar("research", topn=5))

print("\nGensim Skip-gram - research:")
print(skipgram_model.wv.most_similar("research", topn=5))

"""#Gform question solving"""

from gensim.models import Word2Vec

model_300 = Word2Vec(
    sentences=corpus,
    vector_size=300,
    window=5,
    min_count=1,
    sg=0   # CBOW (or sg=1 also fine)
)

word = "student"   # from corpus

vector = model_300.wv[word]
print(len(vector))

print(word, "-", ", ".join(map(str, vector)))

from collections import Counter

counter = Counter(all_tokens)
top10 = counter.most_common(10)

print(top10)